protocols =
listen = 127.0.0.1
base_dir = /run/zp-submission-auth
state_dir = /var/lib/zp-submission-auth
log_path = /dev/stderr
info_log_path = /dev/stderr
ssl = no
auth_mechanisms = plain login
disable_plaintext_auth = yes
auth_username_format = %Lu
auth_verbose_passwords = no
passdb {
  driver = passwd-file
  args = scheme=SHA512-CRYPT username_format=%u /etc/zp-sendas/submission-users
}
userdb {
  driver = static
  args = uid=nobody gid=nogroup home=/nonexistent
}
service auth {
  unix_listener /var/spool/postfix/private/zp-submission-auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}
service auth-worker {
  user = root
}
